# Setup
title:               Test site
tagline:             Musings
description:         Analytics
url:                 https://aoshenz.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Aosh
  url:               https://aoshenz.github.io/
  email:             lol@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
