# Setup
title:               Aoshen
tagline:             Exploring analtyics.
description:         Heya 👋
url:                 https://aoshenz.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Aoshen
  url:               https://aoshenz.github.io
  email:             https://aoshenz.github.io

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: G-HQPY5BS08L
